### ISSUE TITLE
TODO / Ideas

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/FindTextFromVideo#2]
notes

- [ ] Make it faster (too slow for 2hr video..)
- [ ] Add option to output ALL text per frame, into txt file (so can use notepad++ to search strings anytime, instead of always searching again!)
- [ ] option to start/continue from frame number
- [ ] remove search string, since it outputs to text file.. easier to search from there?
- [ ] add github builds
- [ ] ..
